In [1]:
import pandas as pd
import numpy as np

## NumPy көмегімен құруға болады

In [2]:
pd.DataFrame(np.arange(1, 6))

0
0  1
1  2
2  3
3  4
4  5

In [3]:
df = pd.DataFrame(np.arange(1,6))

In [4]:
df

0
0  1
1  2
2  3
3  4
4  5

In [5]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
df.values

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
df.shape

(5, 1)

In [8]:
df = pd.DataFrame(np.array([[10, 11], [20, 21]]))

In [9]:
df

0   1
0  10  11
1  20  21

In [10]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [11]:
df.values

array([[10, 11],
       [20, 21]])

In [12]:
df.shape

(2, 2)

In [13]:
df.ndim

2

In [14]:
df.index.values

array([0, 1])

In [15]:
df.columns

RangeIndex(start=0, stop=2, step=1)

In [16]:
df.columns.values

array([0, 1])

In [18]:
df = pd.DataFrame(np.array([ [70, 71], [90, 91] ]), columns=['Missoula', 'Philadelphia'])

In [19]:
df

Missoula  Philadelphia
0        70            71
1        90            91

In [20]:
df.columns

Index(['Missoula', 'Philadelphia'], dtype='object')

In [21]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [22]:
df.values

array([[70, 71],
       [90, 91]])

In [23]:
len(df)

2

In [24]:
df.size

4

In [25]:
df.shape

(2, 2)

In [26]:
df.ndim

2

## Сөздіктің көмегімен құру

In [28]:
temps_missoula = [70, 71]
temps_philly = [90, 91]
temperatures = {'Missoula': temps_missoula, 'Philadelphia':temps_philly}
df = pd.DataFrame(temperatures)

In [29]:
df

Missoula  Philadelphia
0        70            90
1        71            91

## Series объектісінен тұратын тізімнің көмегімен құру

In [31]:
temps_at_time0 = pd.Series([70, 71])
temps_at_time1 = pd.Series([90, 91])

df = pd.DataFrame([temps_at_time0, temps_at_time1])

In [32]:
df

0   1
0  70  71
1  90  91

In [33]:
df = pd.DataFrame([temps_at_time0, temps_at_time1], columns = ['Missoula', 'Philadelphia'])

In [34]:
df

Missoula  Philadelphia
0       NaN           NaN
1       NaN           NaN

In [35]:
df = pd.DataFrame([temps_at_time0, temps_at_time1])
df.columns = ['Missoula', 'Philadelphia']

In [36]:
df

Missoula  Philadelphia
0        70            71
1        90            91

In [39]:
pd.DataFrame({'Missoula':temps_at_time0, 'Philadelphia':temps_at_time1})

Missoula  Philadelphia
0        70            90
1        71            91

In [40]:
temps_at_time2 = pd.Series([85, 87], index = [1,2])
df = pd.DataFrame({
        'Missoula': temps_at_time0,
        'Philadelphia': temps_at_time1,
        'New York': temps_at_time2
    })
df

Missoula  New York  Philadelphia
0      70.0       NaN          90.0
1      71.0      85.0          91.0
2       NaN      87.0           NaN

## DataFrame-ді CSV файлдан құру

In [41]:
pd.read_csv('DataSets/sp500.csv')

Symbol                          Name                       Sector   Price  \
0      MMM                        3M Co.                  Industrials  141.14   
1      ABT           Abbott Laboratories                  Health Care   39.60   
2     ABBV                   AbbVie Inc.                  Health Care   53.95   
3      ACN                     Accenture       Information Technology   79.79   
4      ACE                   ACE Limited                   Financials  102.91   
5      ACT                   Actavis Inc                  Health Care  213.77   
6     ADBE             Adobe Systems Inc       Information Technology   64.30   
7      AES                      AES Corp                    Utilities   13.61   
8      AET                     Aetna Inc                  Health Care   76.39   
9      AFL                     AFLAC Inc                   Financials   61.31   
10       A      Agilent Technologies Inc                  Health Care   56.18   
11     GAS            AGL Resources Inc.                    Utilities   52.98   
12     APD  Air Products & Chemicals Inc                    Materials  118.74   
13     ARG                    Airgas Inc                    Materials  105.66   
14    AKAM       Akamai Technologies Inc       Information Technology   53.65   
15      AA                     Alcoa Inc                    Materials   13.52   
16    ALXN       Alexion Pharmaceuticals                  Health Care  162.30   
17     ATI    Allegheny Technologies Inc                    Materials   40.99   
18    ALLE                  Allegion plc                  Industrials   52.46   
19     AGN                  Allergan Inc                  Health Care  166.92   
20     ADS    Alliance Data Systems Corp       Information Technology  248.88   
21     ALL                 Allstate Corp                   Financials   58.38   
22    ALTR                   Altera Corp       Information Technology   33.31   
23      MO              Altria Group Inc             Consumer Staples   40.68   
24    AMZN                Amazon.com Inc       Consumer Discretionary  312.24   
25     AEE                   Ameren Corp                    Utilities   38.64   
26     AEP       American Electric Power                    Utilities   51.41   
27     AXP           American Express Co                   Financials   88.78   
28     AIG       American Intl Group Inc                   Financials   53.60   
29     AMT         American Tower Corp A                   Financials   88.41   
..     ...                           ...                          ...     ...   
470   VIAB                   Viacom Inc.       Consumer Discretionary   84.99   
471      V                     Visa Inc.       Information Technology  212.07   
472    VNO          Vornado Realty Trust                   Financials  105.32   
473    VMC              Vulcan Materials                    Materials   61.19   
474    WMT               Wal-Mart Stores             Consumer Staples   75.61   
475    WAG                  Walgreen Co.             Consumer Staples   69.79   
476    DIS               Walt Disney Co.       Consumer Discretionary   83.32   
477     WM         Waste Management Inc.                  Industrials   43.37   
478    WAT            Waters Corporation                  Health Care  100.54   
479    WLP                WellPoint Inc.                  Health Care  108.82   
480    WFC                   Wells Fargo                   Financials   50.16   
481    WDC               Western Digital       Information Technology   84.83   
482     WU              Western Union Co       Information Technology   15.77   
483     WY            Weyerhaeuser Corp.                   Financials   30.87   
484    WHR               Whirlpool Corp.       Consumer Discretionary  147.26   
485    WFM            Whole Foods Market             Consumer Staples   37.78   
486    WIN        Windstream Corporation  Telecommunications Services    9.38   
487    WEC  Wisconsin Energy Corpor

In [42]:
df = pd.read_csv('DataSets/sp500.csv', index_col='Symbol', usecols=[0, 2, 3, 7])
df

Sector   Price  Book Value
Symbol                                                 
MMM                     Industrials  141.14      26.668
ABT                     Health Care   39.60      15.573
ABBV                    Health Care   53.95       2.954
ACN          Information Technology   79.79       8.326
ACE                      Financials  102.91      86.897
ACT                     Health Care  213.77      55.188
ADBE         Information Technology   64.30      13.262
AES                       Utilities   13.61       5.781
AET                     Health Care   76.39      40.021
AFL                      Financials   61.31      34.527
A                       Health Care   56.18      16.928
GAS                       Utilities   52.98      32.462
APD                       Materials  118.74      34.723
ARG                       Materials  105.66      24.882
AKAM         Information Technology   53.65      15.193
AA                        Materials   13.52       9.670
ALXN                    Health Care  162.30      13.628
ATI                       Materials   40.99      26.401
ALLE                    Industrials   52.46       0.000
AGN                     Health Care  166.92      22.207
ADS          Information Technology  248.88      17.392
ALL                      Financials   58.38      47.465
ALTR         Information Technology   33.31      11.026
MO                 Consumer Staples   40.68       2.072
AMZN         Consumer Discretionary  312.24      22.452
AEE                       Utilities   38.64      26.847
AEP                       Utilities   51.41      33.635
AXP                      Financials   88.78      18.846
AIG                      Financials   53.60      71.775
AMT                      Financials   88.41       9.279
...                             ...     ...         ...
VIAB         Consumer Discretionary   84.99      10.253
V            Information Technology  212.07      43.391
VNO                      Financials  105.32      28.243
VMC                       Materials   61.19      30.819
WMT                Consumer Staples   75.61      22.607
WAG                Consumer Staples   69.79      21.779
DIS          Consumer Discretionary   83.32      26.405
WM                      Industrials   43.37      12.330
WAT                     Health Care  100.54      21.460
WLP                     Health Care  108.82      86.358
WFC                      Financials   50.16      30.479
WDC          Information Technology   84.83      37.311
WU           Information Technology   15.77       1.981
WY                       Financials   30.87      11.690
WHR          Consumer Discretionary  147.26      66.221
WFM                Consumer Staples   37.78      10.867
WIN     Telecommunications Services    9.38       1.199
WEC                       Utilities   45.13      19.165
WYN          Consumer Discretionary   72.22      11.984
WYNN         Consumer Discretionary  207.86      -0.719
XEL                       Utilities   30.24      19.450
XRX          Information Technology   12.06      10.471
XLNX         Information Technology   46.03      10.247
XL                       Financials   32.47      37.451
XYL                     Industrials   38.42      12.127
YHOO         Information Technology   35.02      12.768
YUM          Consumer Discretionary   74.77       5.147
ZMH                     Health Care  101.84      37.181
ZION                     Financials   28.43      30.191
ZTS                     Health Care   30.53       2.150

[500 rows x 3 columns]

In [43]:
len(df)

500

In [44]:
df.size

1500

In [45]:
df.shape

(500, 3)

In [46]:
df.index

Index(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ACT', 'ADBE', 'AES', 'AET', 'AFL',
       ...
       'XEL', 'XRX', 'XLNX', 'XL', 'XYL', 'YHOO', 'YUM', 'ZMH', 'ZION', 'ZTS'],
      dtype='object', name='Symbol', length=500)

In [47]:
df.columns

Index(['Sector', 'Price', 'Book Value'], dtype='object')

In [48]:
df.values

array([['Industrials', 141.14, 26.668000000000003],
       ['Health Care', 39.6, 15.573],
       ['Health Care', 53.95, 2.9539999999999997],
       ...,
       ['Health Care', 101.84, 37.181],
       ['Financials', 28.43, 30.191],
       ['Health Care', 30.53, 2.15]], dtype=object)